package com.ciro.app.util

import android.content.Context
import android.content.Intent
import android.net.Uri
import com.ciro.app.data.model.Incident

/**
 * Centralized Android intent helpers for emergency responder actions.
 * Navigate, Call, and Share — one tap each.
 */
object IntentUtils {

    /**
     * Opens Google Maps with driving navigation to the given coordinates.
     * Falls back to a regular map view if Google Maps is not installed.
     */
    fun openNavigation(context: Context, lat: Double, lng: Double, label: String = "") {
        val uri = Uri.parse("google.navigation:q=$lat,$lng&mode=d")
        val intent = Intent(Intent.ACTION_VIEW, uri).apply {
            setPackage("com.google.android.apps.maps")
        }
        if (intent.resolveActivity(context.packageManager) != null) {
            context.startActivity(intent)
        } else {
            // Fallback: open in browser
            val webUri = Uri.parse("https://maps.google.com/maps?daddr=$lat,$lng&dirflg=d")
            context.startActivity(Intent(Intent.ACTION_VIEW, webUri))
        }
    }

    /**
     * Opens the phone dialer with the given number pre-filled.
     * Does NOT auto-dial — the user must press call.
     */
    fun openDialer(context: Context, phoneNumber: String) {
        val intent = Intent(Intent.ACTION_DIAL).apply {
            data = Uri.parse("tel:${phoneNumber.trim()}")
        }
        context.startActivity(intent)
    }

    /**
     * Shares a formatted incident report via Android Share Sheet.
     * Lets the responder send via WhatsApp, SMS, Email, etc.
     */
    fun shareIncidentReport(context: Context, incident: Incident) {
        val confidence = String.format("%.0f", incident.confidence_score * 100)
        val mapsLink = "https://maps.google.com/?q=${incident.location.lat},${incident.location.lng}"

        val report = buildString {
            appendLine("🚨 CIRO INCIDENT REPORT")
            appendLine("━━━━━━━━━━━━━━━━━━━━━━")
            appendLine("Type: ${incident.crisis_type.uppercase().replace("_", " ")}")
            appendLine("Severity: ${incident.severity_level}/5 (${incident.severityLabel})")
            appendLine("Status: ${incident.state.replace("_", " ")}")
            appendLine()
            appendLine("📍 Location: ${incident.location.area_name.ifBlank { "Islamabad" }}")
            appendLine("   Coordinates: ${incident.location.lat}, ${incident.location.lng}")
            appendLine("   Radius: ${incident.location.affected_radius_km}km")
            appendLine()
            appendLine("👥 Affected: ${incident.affected_population_estimate} people")
            appendLine("⏱️ Duration: ${incident.expected_duration_hours}h")
            appendLine("📡 Spread Risk: ${incident.spread_risk.uppercase()}")
            appendLine("🎯 AI Confidence: $confidence%")
            appendLine("🛡️ Resources: ${incident.resources_allocated.size} units deployed")
            appendLine()
            appendLine("🧭 Navigate: $mapsLink")
            appendLine()
            appendLine("— Generated by CIRO (Crisis Intelligence & Response Orchestrator)")
        }

        val sendIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, "🚨 CIRO: ${incident.crisis_type.uppercase()} in ${incident.location.area_name}")
            putExtra(Intent.EXTRA_TEXT, report)
        }
        context.startActivity(Intent.createChooser(sendIntent, "Share Incident Report"))
    }
}
